// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.4
// source: usersinfo.proto

package usersinfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsersInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *UsersInfoRequest) Reset() {
	*x = UsersInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usersinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersInfoRequest) ProtoMessage() {}

func (x *UsersInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usersinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersInfoRequest.ProtoReflect.Descriptor instead.
func (*UsersInfoRequest) Descriptor() ([]byte, []int) {
	return file_usersinfo_proto_rawDescGZIP(), []int{0}
}

func (x *UsersInfoRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Channel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *Channel) Reset() {
	*x = Channel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usersinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_usersinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_usersinfo_proto_rawDescGZIP(), []int{1}
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UsersInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth    bool     `protobuf:"varint,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Twitch  *Channel `protobuf:"bytes,2,opt,name=Twitch,proto3" json:"Twitch,omitempty"`
	Youtube *Channel `protobuf:"bytes,3,opt,name=Youtube,proto3" json:"Youtube,omitempty"`
	Aparat  *Channel `protobuf:"bytes,4,opt,name=Aparat,proto3" json:"Aparat,omitempty"`
}

func (x *UsersInfoResponse) Reset() {
	*x = UsersInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_usersinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersInfoResponse) ProtoMessage() {}

func (x *UsersInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usersinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersInfoResponse.ProtoReflect.Descriptor instead.
func (*UsersInfoResponse) Descriptor() ([]byte, []int) {
	return file_usersinfo_proto_rawDescGZIP(), []int{2}
}

func (x *UsersInfoResponse) GetAuth() bool {
	if x != nil {
		return x.Auth
	}
	return false
}

func (x *UsersInfoResponse) GetTwitch() *Channel {
	if x != nil {
		return x.Twitch
	}
	return nil
}

func (x *UsersInfoResponse) GetYoutube() *Channel {
	if x != nil {
		return x.Youtube
	}
	return nil
}

func (x *UsersInfoResponse) GetAparat() *Channel {
	if x != nil {
		return x.Aparat
	}
	return nil
}

var File_usersinfo_proto protoreflect.FileDescriptor

var file_usersinfo_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x24, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2f, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x8f, 0x01, 0x0a, 0x11, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x12, 0x20, 0x0a, 0x06, 0x54, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x06, 0x54, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x12, 0x22, 0x0a, 0x07, 0x59, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52,
	0x07, 0x59, 0x6f, 0x75, 0x74, 0x75, 0x62, 0x65, 0x12, 0x20, 0x0a, 0x06, 0x41, 0x70, 0x61, 0x72,
	0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x06, 0x41, 0x70, 0x61, 0x72, 0x61, 0x74, 0x32, 0x39, 0x0a, 0x09, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x11,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x73, 0x69, 0x6e,
	0x66, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_usersinfo_proto_rawDescOnce sync.Once
	file_usersinfo_proto_rawDescData = file_usersinfo_proto_rawDesc
)

func file_usersinfo_proto_rawDescGZIP() []byte {
	file_usersinfo_proto_rawDescOnce.Do(func() {
		file_usersinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_usersinfo_proto_rawDescData)
	})
	return file_usersinfo_proto_rawDescData
}

var file_usersinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_usersinfo_proto_goTypes = []interface{}{
	(*UsersInfoRequest)(nil),  // 0: UsersInfoRequest
	(*Channel)(nil),           // 1: Channel
	(*UsersInfoResponse)(nil), // 2: UsersInfoResponse
}
var file_usersinfo_proto_depIdxs = []int32{
	1, // 0: UsersInfoResponse.Twitch:type_name -> Channel
	1, // 1: UsersInfoResponse.Youtube:type_name -> Channel
	1, // 2: UsersInfoResponse.Aparat:type_name -> Channel
	0, // 3: UsersInfo.Get:input_type -> UsersInfoRequest
	2, // 4: UsersInfo.Get:output_type -> UsersInfoResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_usersinfo_proto_init() }
func file_usersinfo_proto_init() {
	if File_usersinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_usersinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usersinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Channel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_usersinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usersinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usersinfo_proto_goTypes,
		DependencyIndexes: file_usersinfo_proto_depIdxs,
		MessageInfos:      file_usersinfo_proto_msgTypes,
	}.Build()
	File_usersinfo_proto = out.File
	file_usersinfo_proto_rawDesc = nil
	file_usersinfo_proto_goTypes = nil
	file_usersinfo_proto_depIdxs = nil
}
