// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: usersinfo.proto

package usersinfo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsersInfoClient is the client API for UsersInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersInfoClient interface {
	Get(ctx context.Context, in *UsersInfoRequest, opts ...grpc.CallOption) (*UsersInfoResponse, error)
}

type usersInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersInfoClient(cc grpc.ClientConnInterface) UsersInfoClient {
	return &usersInfoClient{cc}
}

func (c *usersInfoClient) Get(ctx context.Context, in *UsersInfoRequest, opts ...grpc.CallOption) (*UsersInfoResponse, error) {
	out := new(UsersInfoResponse)
	err := c.cc.Invoke(ctx, "/UsersInfo/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersInfoServer is the server API for UsersInfo service.
// All implementations must embed UnimplementedUsersInfoServer
// for forward compatibility
type UsersInfoServer interface {
	Get(context.Context, *UsersInfoRequest) (*UsersInfoResponse, error)
	mustEmbedUnimplementedUsersInfoServer()
}

// UnimplementedUsersInfoServer must be embedded to have forward compatible implementations.
type UnimplementedUsersInfoServer struct {
}

func (UnimplementedUsersInfoServer) Get(context.Context, *UsersInfoRequest) (*UsersInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedUsersInfoServer) mustEmbedUnimplementedUsersInfoServer() {}

// UnsafeUsersInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersInfoServer will
// result in compilation errors.
type UnsafeUsersInfoServer interface {
	mustEmbedUnimplementedUsersInfoServer()
}

func RegisterUsersInfoServer(s grpc.ServiceRegistrar, srv UsersInfoServer) {
	s.RegisterService(&UsersInfo_ServiceDesc, srv)
}

func _UsersInfo_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersInfoServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UsersInfo/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersInfoServer).Get(ctx, req.(*UsersInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersInfo_ServiceDesc is the grpc.ServiceDesc for UsersInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UsersInfo",
	HandlerType: (*UsersInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UsersInfo_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usersinfo.proto",
}
